### ISSUE TITLE
测试数据

### ISSUE THREAD

**Issue by MrJackC** [qccadmin/ExamOnline-SSM#2]
您好！
我在本地部署了您的项目，但是数据脚本只有表结构，可否提供一下测试数据！谢谢

**Comment by PPQQXX** [comment]
这个你跑的起来吗？

**Comment by MrJackC** [comment]
跑起来了呀

> 这个你跑的起来吗？

**Comment by PPQQXX** [comment]
登录不了算吗，stu:null

**Comment by PPQQXX** [comment]
现在感觉有点蒙

**Comment by PPQQXX** [comment]
请问你的运行环境是怎样的？求告知
输入后就出现这个，ascii为44的字符是“，”，说明cookie不支持“，”
严重:java.lang.IllegalArgumentException: An invalid character [44] was present in the Cookie value

**Comment by PPQQXX** [comment]
害，我咋学生登录不上去，老师和管理员都行呢，大哥帮帮忙

**Comment by PPQQXX** [comment]
对不起，打扰了。万万没想到学生登录的检测，剧毒

**Comment by yhc115799** [comment]
为什么我跑起来登录功能不好使呢

**Comment by yhc115799** [comment]
你们的登录成功能实现页面跳转吗

**Comment by MrJackC** [comment]
> 你们的登录成功能实现页面跳转吗

当时就是部署的玩儿了玩儿  我记得功能还都算正常，时间长了 忘记了什么情况了 自己可以调试一下看看，很简单的项目。

**Comment by yhc115799** [comment]
项目可以跑起来，但是我觉得他这个登录功能有问题，我也没改好。哥们有时间能再跑一次试试吗。
